# fly.toml app configuration file generated for automower-watchdog on 2025-07-29T07:18:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'automower-watchdog'
primary_region = 'arn'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
