# fly.toml app configuration file generated for automower-watchdog on 2025-07-29T07:10:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'automower-watchdog'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
